services:
  client:
    build:
      context: .
      target: development  # Use the 'development' stage from Dockerfile.prod for development
    command: npm run dev
    user: 1000:1000  # Use the same user as the host
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/app:rw

  